# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.runs/synth_1/CSSTE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.cache/wt [current_project]
set_property parent.project_path D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_repo_paths d:/COLab/OExp02-IP2SOC/IP [current_project]
update_ip_catalog
set_property ip_output_repo d:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/COLab/OExp02-IP2SOC/IP/I_mem.coe
add_files D:/COLab/OExp02-IP2SOC/IP/D_mem.coe
read_mem {
  D:/COLab/OExp02-IP2SOC/IP/vga_debugger.mem
  D:/COLab/OExp02-IP2SOC/IP/font_8x16.mem
}
read_verilog -library xil_defaultlib {
  D:/COLab/OExp02-IP2SOC/IP/Counter_x.v
  D:/COLab/OExp02-IP2SOC/IP/Hex2Ascii.v
  D:/COLab/OExp02-IP2SOC/IP/MIO_BUS.v
  D:/COLab/OExp02-IP2SOC/IP/Multi_8CH32.v
  D:/COLab/OExp02-IP2SOC/IP/SAnti_jitter.v
  D:/COLab/OExp02-IP2SOC/IP/SCPU.v
  D:/COLab/OExp02-IP2SOC/IP/SPIO.v
  D:/COLab/OExp02-IP2SOC/IP/VGA.v
  D:/COLab/OExp02-IP2SOC/IP/VgaController.v
  D:/COLab/OExp02-IP2SOC/IP/VgaDebugger.v
  D:/COLab/OExp02-IP2SOC/IP/VgaDisplay.v
  D:/COLab/OExp02-IP2SOC/IP/clk_div.v
  D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/new/CSSTE.v
}
read_ip -quiet D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/Seg7_Dev_0/Seg7_Dev_0.xci

read_ip -quiet D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_ip -quiet D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all d:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_edif D:/COLab/OExp02-IP2SOC/IP/Counter_x.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/SAnti_jitter.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/clk_div.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/SPIO.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/Multi_8CH32.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/MIO_BUS.edf
read_edif D:/COLab/OExp02-IP2SOC/IP/SCPU.edf
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/COLab/OExp02-IP2SOC/IP/A7.xdc
set_property used_in_implementation false [get_files D:/COLab/OExp02-IP2SOC/IP/A7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/COLab/OExp02-IP2SOC/OExp02-IP2SOC.srcs/utils_1/imports/synth_1/CSSTE.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CSSTE -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSSTE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSSTE_utilization_synth.rpt -pb CSSTE_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
